### PR TITLE
fix typo (from `sourcePreviewNodeOptions` to `sourcePreviewNodesOptio…

### PR DESCRIPTION
**Pull request by anatoliyarkhipov**
This PR fixes typos in the `connectDragPreview` method.

And thanks for the package, I even cannot calculate how many hours did it save for our team.

### CODE REVIEW

**Comment by zyzo** [comment]
Thanks for the fix ! And I'm very glad to hear the library helped, we used it internally to compensate the shortcomings of html5 dnd api as well. Please don't hesitate if you find any bug / edge case with this library.

**Comment by anatoliyarkhipov** [comment]
Thanks, @zyzo! Also, is it possible to bump the version to make it easy to update the package using NPM? It also can help if someone find this package and just install the latest version.

**Comment by zyzo** [comment]
Done.

**Comment by anatoliyarkhipov** [comment]
Sorry for bothering, but I think you should also run `npm publish`, because it still be `0.1.0` in the registry :sweat_smile:
https://www.npmjs.com/package/react-dnd-mouse-backend

**Comment by zyzo** [comment]
Yep, my bad 😜

**Pull request merged**
